//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Business.Contracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class AttributeDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AllowsMultipleValuesField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowsMultipleValues
        {
            get
            {
                return this.AllowsMultipleValuesField;
            }
            set
            {
                this.AllowsMultipleValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResult", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyPhotos.Business.Contracts.ApiResultOfFileDtoRYvytkfI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyPhotos.Business.Contracts.ApiResultOfAttributeDtoRYvytkfI))]
    public partial class ApiResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorField;
        
        private bool IsFailureField;
        
        private bool IsSuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFailure
        {
            get
            {
                return this.IsFailureField;
            }
            set
            {
                this.IsFailureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfFileDtoRYvytkfI", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class ApiResultOfFileDtoRYvytkfI : MyPhotos.Business.Contracts.ApiResult
    {
        
        private MyPhotos.Business.Contracts.FileDto ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Business.Contracts.FileDto Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfAttributeDtoRYvytkfI", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class ApiResultOfAttributeDtoRYvytkfI : MyPhotos.Business.Contracts.ApiResult
    {
        
        private MyPhotos.Business.Contracts.AttributeDto ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Business.Contracts.AttributeDto Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class FileDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private MyPhotos.Business.Contracts.FileAttributeDto[] AttributesField;
        
        private System.DateTime CreatedAtField;
        
        private System.Guid IdField;
        
        private string PathField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Business.Contracts.FileAttributeDto[] Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAttributeDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class FileAttributeDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid AttributeIdField;
        
        private string AttributeNameField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AttributeId
        {
            get
            {
                return this.AttributeIdField;
            }
            set
            {
                this.AttributeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeName
        {
            get
            {
                return this.AttributeNameField;
            }
            set
            {
                this.AttributeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyPhotosFacade")]
public interface IMyPhotosFacade
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/GetAttributes", ReplyAction="http://tempuri.org/IAttributesService/GetAttributesResponse")]
    MyPhotos.Business.Contracts.AttributeDto[] GetAttributes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/GetAttributes", ReplyAction="http://tempuri.org/IAttributesService/GetAttributesResponse")]
    System.Threading.Tasks.Task<MyPhotos.Business.Contracts.AttributeDto[]> GetAttributesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/CreateAttribute", ReplyAction="http://tempuri.org/IAttributesService/CreateAttributeResponse")]
    MyPhotos.Business.Contracts.ApiResultOfAttributeDtoRYvytkfI CreateAttribute(MyPhotos.Business.Contracts.AttributeDto dto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/CreateAttribute", ReplyAction="http://tempuri.org/IAttributesService/CreateAttributeResponse")]
    System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResultOfAttributeDtoRYvytkfI> CreateAttributeAsync(MyPhotos.Business.Contracts.AttributeDto dto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/DeleteAttribute", ReplyAction="http://tempuri.org/IAttributesService/DeleteAttributeResponse")]
    MyPhotos.Business.Contracts.ApiResult DeleteAttribute(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/DeleteAttribute", ReplyAction="http://tempuri.org/IAttributesService/DeleteAttributeResponse")]
    System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResult> DeleteAttributeAsync(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/GetPhotos", ReplyAction="http://tempuri.org/IPhotosService/GetPhotosResponse")]
    MyPhotos.Business.Contracts.FileDto[] GetPhotos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/GetPhotos", ReplyAction="http://tempuri.org/IPhotosService/GetPhotosResponse")]
    System.Threading.Tasks.Task<MyPhotos.Business.Contracts.FileDto[]> GetPhotosAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/CreatePhoto", ReplyAction="http://tempuri.org/IPhotosService/CreatePhotoResponse")]
    MyPhotos.Business.Contracts.ApiResultOfFileDtoRYvytkfI CreatePhoto(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/CreatePhoto", ReplyAction="http://tempuri.org/IPhotosService/CreatePhotoResponse")]
    System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResultOfFileDtoRYvytkfI> CreatePhotoAsync(string path);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/DeletePhoto", ReplyAction="http://tempuri.org/IPhotosService/DeletePhotoResponse")]
    MyPhotos.Business.Contracts.ApiResult DeletePhoto(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/DeletePhoto", ReplyAction="http://tempuri.org/IPhotosService/DeletePhotoResponse")]
    System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResult> DeletePhotoAsync(System.Guid id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyPhotosFacadeChannel : IMyPhotosFacade, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyPhotosFacadeClient : System.ServiceModel.ClientBase<IMyPhotosFacade>, IMyPhotosFacade
{
    
    public MyPhotosFacadeClient()
    {
    }
    
    public MyPhotosFacadeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyPhotosFacadeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyPhotosFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyPhotosFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MyPhotos.Business.Contracts.AttributeDto[] GetAttributes()
    {
        return base.Channel.GetAttributes();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Business.Contracts.AttributeDto[]> GetAttributesAsync()
    {
        return base.Channel.GetAttributesAsync();
    }
    
    public MyPhotos.Business.Contracts.ApiResultOfAttributeDtoRYvytkfI CreateAttribute(MyPhotos.Business.Contracts.AttributeDto dto)
    {
        return base.Channel.CreateAttribute(dto);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResultOfAttributeDtoRYvytkfI> CreateAttributeAsync(MyPhotos.Business.Contracts.AttributeDto dto)
    {
        return base.Channel.CreateAttributeAsync(dto);
    }
    
    public MyPhotos.Business.Contracts.ApiResult DeleteAttribute(System.Guid id)
    {
        return base.Channel.DeleteAttribute(id);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResult> DeleteAttributeAsync(System.Guid id)
    {
        return base.Channel.DeleteAttributeAsync(id);
    }
    
    public MyPhotos.Business.Contracts.FileDto[] GetPhotos()
    {
        return base.Channel.GetPhotos();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Business.Contracts.FileDto[]> GetPhotosAsync()
    {
        return base.Channel.GetPhotosAsync();
    }
    
    public MyPhotos.Business.Contracts.ApiResultOfFileDtoRYvytkfI CreatePhoto(string path)
    {
        return base.Channel.CreatePhoto(path);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResultOfFileDtoRYvytkfI> CreatePhotoAsync(string path)
    {
        return base.Channel.CreatePhotoAsync(path);
    }
    
    public MyPhotos.Business.Contracts.ApiResult DeletePhoto(System.Guid id)
    {
        return base.Channel.DeletePhoto(id);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Business.Contracts.ApiResult> DeletePhotoAsync(System.Guid id)
    {
        return base.Channel.DeletePhotoAsync(id);
    }
}
