//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class AttributeDto : object
    {
        
        private bool AllowsMultipleValuesField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowsMultipleValues
        {
            get
            {
                return this.AllowsMultipleValuesField;
            }
            set
            {
                this.AllowsMultipleValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResult", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyPhotos.ApiResultOfFileDtoRYvytkfI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyPhotos.ApiResultOfAttributeDtoRYvytkfI))]
    public partial class ApiResult : object
    {
        
        private string ErrorField;
        
        private bool IsFailureField;
        
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFailure
        {
            get
            {
                return this.IsFailureField;
            }
            set
            {
                this.IsFailureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfFileDtoRYvytkfI", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class ApiResultOfFileDtoRYvytkfI : MyPhotos.ApiResult
    {
        
        private MyPhotos.FileDto ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.FileDto Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResultOfAttributeDtoRYvytkfI", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class ApiResultOfAttributeDtoRYvytkfI : MyPhotos.ApiResult
    {
        
        private MyPhotos.AttributeDto ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.AttributeDto Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class FileDto : object
    {
        
        private System.Collections.Generic.List<MyPhotos.FileAttributeDto> AttributesField;
        
        private System.DateTime CreatedAtField;
        
        private System.Guid IdField;
        
        private string PathField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotos.FileAttributeDto> Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAttributeDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Business.Contracts")]
    public partial class FileAttributeDto : object
    {
        
        private System.Guid AttributeIdField;
        
        private string AttributeNameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AttributeId
        {
            get
            {
                return this.AttributeIdField;
            }
            set
            {
                this.AttributeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeName
        {
            get
            {
                return this.AttributeNameField;
            }
            set
            {
                this.AttributeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyPhotos.IMyPhotosFacade")]
    public interface IMyPhotosFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/GetAttributes", ReplyAction="http://tempuri.org/IAttributesService/GetAttributesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.AttributeDto>> GetAttributesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/CreateAttribute", ReplyAction="http://tempuri.org/IAttributesService/CreateAttributeResponse")]
        System.Threading.Tasks.Task<MyPhotos.ApiResultOfAttributeDtoRYvytkfI> CreateAttributeAsync(MyPhotos.AttributeDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/GetAllAttributesValues", ReplyAction="http://tempuri.org/IAttributesService/GetAllAttributesValuesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.FileAttributeDto>> GetAllAttributesValuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttributesService/DeleteAttribute", ReplyAction="http://tempuri.org/IAttributesService/DeleteAttributeResponse")]
        System.Threading.Tasks.Task<MyPhotos.ApiResult> DeleteAttributeAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/GetPhotos", ReplyAction="http://tempuri.org/IPhotosService/GetPhotosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.FileDto>> GetPhotosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/FindByKeyword", ReplyAction="http://tempuri.org/IPhotosService/FindByKeywordResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.FileDto>> FindByKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/CreatePhoto", ReplyAction="http://tempuri.org/IPhotosService/CreatePhotoResponse")]
        System.Threading.Tasks.Task<MyPhotos.ApiResultOfFileDtoRYvytkfI> CreatePhotoAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/ChangeTitle", ReplyAction="http://tempuri.org/IPhotosService/ChangeTitleResponse")]
        System.Threading.Tasks.Task<MyPhotos.ApiResultOfFileDtoRYvytkfI> ChangeTitleAsync(System.Guid id, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/AddAttributeValue", ReplyAction="http://tempuri.org/IPhotosService/AddAttributeValueResponse")]
        System.Threading.Tasks.Task<MyPhotos.ApiResultOfFileDtoRYvytkfI> AddAttributeValueAsync(System.Guid id, System.Guid attributeId, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotosService/DeletePhoto", ReplyAction="http://tempuri.org/IPhotosService/DeletePhotoResponse")]
        System.Threading.Tasks.Task<MyPhotos.ApiResult> DeletePhotoAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IMyPhotosFacadeChannel : MyPhotos.IMyPhotosFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class MyPhotosFacadeClient : System.ServiceModel.ClientBase<MyPhotos.IMyPhotosFacade>, MyPhotos.IMyPhotosFacade
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyPhotosFacadeClient() : 
                base(MyPhotosFacadeClient.GetDefaultBinding(), MyPhotosFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMyPhotosFacade.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(MyPhotosFacadeClient.GetBindingForEndpoint(endpointConfiguration), MyPhotosFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyPhotosFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyPhotosFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.AttributeDto>> GetAttributesAsync()
        {
            return base.Channel.GetAttributesAsync();
        }
        
        public System.Threading.Tasks.Task<MyPhotos.ApiResultOfAttributeDtoRYvytkfI> CreateAttributeAsync(MyPhotos.AttributeDto dto)
        {
            return base.Channel.CreateAttributeAsync(dto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.FileAttributeDto>> GetAllAttributesValuesAsync()
        {
            return base.Channel.GetAllAttributesValuesAsync();
        }
        
        public System.Threading.Tasks.Task<MyPhotos.ApiResult> DeleteAttributeAsync(System.Guid id)
        {
            return base.Channel.DeleteAttributeAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.FileDto>> GetPhotosAsync()
        {
            return base.Channel.GetPhotosAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotos.FileDto>> FindByKeywordAsync(string keyword)
        {
            return base.Channel.FindByKeywordAsync(keyword);
        }
        
        public System.Threading.Tasks.Task<MyPhotos.ApiResultOfFileDtoRYvytkfI> CreatePhotoAsync(string path)
        {
            return base.Channel.CreatePhotoAsync(path);
        }
        
        public System.Threading.Tasks.Task<MyPhotos.ApiResultOfFileDtoRYvytkfI> ChangeTitleAsync(System.Guid id, string title)
        {
            return base.Channel.ChangeTitleAsync(id, title);
        }
        
        public System.Threading.Tasks.Task<MyPhotos.ApiResultOfFileDtoRYvytkfI> AddAttributeValueAsync(System.Guid id, System.Guid attributeId, string value)
        {
            return base.Channel.AddAttributeValueAsync(id, attributeId, value);
        }
        
        public System.Threading.Tasks.Task<MyPhotos.ApiResult> DeletePhotoAsync(System.Guid id)
        {
            return base.Channel.DeletePhotoAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMyPhotosFacade))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMyPhotosFacade))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MyPhotosFacadeClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMyPhotosFacade);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MyPhotosFacadeClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMyPhotosFacade);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMyPhotosFacade,
        }
    }
}
