//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public System.Guid Id { get; private set; }
        public string Name { get; private set; }
        public bool AllowsMultipleValues { get; private set; }
        public bool IsDeleted { get; private set; }
    }
}
