//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttribute
    {
        public System.Guid Id { get; private set; }
        public string Value { get; private set; }
        public Nullable<System.Guid> AttributeId { get; private set; }
        public System.Guid FileId { get; private set; }
    
        public virtual Attribute Attribute { get; private set; }
        public virtual File File { get; private set; }
    }
}
